### ISSUE TITLE
Restarting docker image keeps appending to axonserver.properties instead of replacing entries

### ISSUE THREAD

**Issue by GSamuel** [AxonIQ/axon-server-dockerfile#5]
After using docker-compose stop and docker-compose up multiple times the axonserver.properties file now contains multiple entries of the same properties.

docker-compose.yml
```
version: '3'
services:
  axon-server:
    image: "axoniq/axonserver"
    ports:
      - "8024:8024"
      - "8124:8124"
```

axonserver.properties
```
axoniq.axonserver.accesscontrol.enabled=false
axoniq.axonserver.accesscontrol.token=

axoniq.axonserver.accesscontrol.enabled=false
axoniq.axonserver.accesscontrol.token=

axoniq.axonserver.accesscontrol.enabled=false
axoniq.axonserver.accesscontrol.token=

axoniq.axonserver.accesscontrol.enabled=false
axoniq.axonserver.accesscontrol.token=

axoniq.axonserver.accesscontrol.enabled=false
axoniq.axonserver.accesscontrol.token=
```
